apiVersion: apps/v1
kind: Deployment
metadata:
  name: userms-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userms
  template:
    metadata:
      labels:
        app: userms
    spec:
      containers:
      - name: userms-container
        image: docker.io/nitishbits/userms-i:latest
        ports:
        - containerPort: 3001
        readinessProbe:
          httpGet:
            path: /health-check
            port: 3001
          initialDelaySeconds: 20
          periodSeconds: 30
          failureThreshold: 5
---
apiVersion: v1
kind: Service
metadata:
  name: userms-service
spec:
  selector:
    app: userms
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: NodePort
  selector:
    app: userms
