apiVersion: apps/v1
kind: Deployment
metadata:
  name: userdb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userdb
  template:
    metadata:
      labels:
        app: userdb
    spec:
      containers:
      - name: userdb-c
        image: docker.io/nitishbits/userdb-i:latest
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: userdb-service
spec:
  selector:
    app: userdb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
