# Use the official MySQL image as the parent image
FROM mysql:latest

# Environment variables for MySQL configuration
ENV MYSQL_ROOT_PASSWORD=rootmysqldb
ENV MYSQL_DATABASE=user_db
ENV MYSQL_USER=nitish
ENV MYSQL_PASSWORD=usermysqldb

# Copy SQL scripts to import data
COPY ./schema.sql /docker-entrypoint-initdb.d/

# Expose the MySQL port
EXPOSE 3306

# Start MySQL service
CMD ["mysqld"]
