name: Test and Publish User Microservice Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'

jobs:

  run-unit-tests:
    name: Perform Unit Testing
    uses: ./.github/workflows/test.yml

  publish-docker-image:
    name: Publish Docker Image
    needs: run-unit-tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: nitishbits/userms-i:latest